#include <vision_node.h>

class ExampleVisionAction{

    protected:

    ros::NodeHandle nh_; //still need to pass a node in (maybe make this a pointer?)

    //is this a reference to the autogenerated 
    actionlib::SimpleActionServer<ram_msgs::exampleVisionAction> as_;

}
    
