
#define QUBOBUS_PROTOCOL_VERSION 1

#define QUBOBUS_MESSAGE_TYPES 6
#define QUBOBUS_DATA_TYPES 80
#define QUBOBUS_ERROR_TYPES 80

#define QUBOBUS_ANNOUNCE_INTERVAL_S 5
#define QUBOBUS_KEEPALIVE_INTERVAL_S 1
